Repository UMC-partNerd/backend, pull requests merged in 2025-01, with the labels that each got.

#14 [FEAT] 마이페이지 내프로필 조회/수정 API 구현 (#4)
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/apiPaylaod/exception/handler/MemberHandler.java
  src/main/java/com/partnerd/converter/MemberConverter.java
  src/main/java/com/partnerd/domain/Agreements.java
  src/main/java/com/partnerd/domain/Member.java
  src/main/java/com/partnerd/repository/agreementsRepository/AgreementsRepository.java
  src/main/java/com/partnerd/service/memberService/MemberService.java
  src/main/java/com/partnerd/service/memberService/MemberServiceImpl.java
  src/main/java/com/partnerd/web/controller/MemberRestController.java
  src/main/java/com/partnerd/web/dto/memberDTO/MemberRequestDTO.java
  src/main/java/com/partnerd/web/dto/memberDTO/MemberResponseDTO.java
Labels: :sparkles: Feature

#17 [FEAT] 동아리(파트너드) 등록/삭제/수정 API 구현 (#13)
  src/main/generated/com/partnerd/domain/QAgreements.java
  src/main/generated/com/partnerd/domain/QAlarm.java
  src/main/generated/com/partnerd/domain/QClub.java
  src/main/generated/com/partnerd/domain/QClubActivity.java
  src/main/generated/com/partnerd/domain/QClubActivityImage.java
  src/main/generated/com/partnerd/domain/QClubImage.java
  src/main/generated/com/partnerd/domain/QCollabInquiry.java
  src/main/generated/com/partnerd/domain/QCollabPost.java
  src/main/generated/com/partnerd/domain/QCommunity.java
  src/main/generated/com/partnerd/domain/QCommunityComment.java
  src/main/generated/com/partnerd/domain/QCommunityImage.java
  src/main/generated/com/partnerd/domain/QEventImage.java
  src/main/generated/com/partnerd/domain/QEventType.java
  src/main/generated/com/partnerd/domain/QMember.java
  src/main/generated/com/partnerd/domain/QPersonal.java
  src/main/generated/com/partnerd/domain/QPersonalLink.java
  src/main/generated/com/partnerd/domain/QProject.java
  src/main/generated/com/partnerd/domain/QProjectComment.java
  src/main/generated/com/partnerd/domain/QProjectImage.java
  src/main/generated/com/partnerd/domain/QProjectRole.java
  src/main/generated/com/partnerd/domain/QPromotionProject.java
  src/main/generated/com/partnerd/domain/QPromotionProjectComment.java
  src/main/generated/com/partnerd/domain/QPromotionProjectImage.java
  src/main/generated/com/partnerd/domain/QPromotionProjectRole.java
  src/main/generated/com/partnerd/domain/common/QBaseEntity.java
  src/main/generated/com/partnerd/domain/mapping/QClubMember.java
  src/main/generated/com/partnerd/domain/mapping/QClubMembershipRequest.java
  src/main/generated/com/partnerd/domain/mapping/QCollabRequest.java
  src/main/generated/com/partnerd/domain/mapping/QProjectMember.java
  src/main/generated/com/partnerd/domain/mapping/QPromotionProjectMember.java
  src/main/java/com/partnerd/converter/ClubConverter.java
  src/main/java/com/partnerd/domain/Club.java
  src/main/java/com/partnerd/domain/ClubActivity.java
  src/main/java/com/partnerd/repository/clubRepository/ClubRepository.java
  src/main/java/com/partnerd/service/clubService/ClubService.java
  src/main/java/com/partnerd/service/clubService/ClubServiceImpl.java
  src/main/java/com/partnerd/web/controller/ClubRestController.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubRegisterRequestDTO.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubRegisterResponseDTO.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubUpdateRequestDTO.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubUpdateResponseDTO.java
Labels: :sparkles: Feature

#20 [REFACTOR] 자동 객체 관리를 통해 명시적인 삭제 작업 제거 및 CollabPostRequestDTO 필드타입 수정
  src/main/generated/com/partnerd/domain/QAgreements.java
  src/main/generated/com/partnerd/domain/QAlarm.java
  src/main/generated/com/partnerd/domain/QCategory.java
  src/main/generated/com/partnerd/domain/QClub.java
  src/main/generated/com/partnerd/domain/QClubActivity.java
  src/main/generated/com/partnerd/domain/QClubActivityImage.java
  src/main/generated/com/partnerd/domain/QClubImage.java
  src/main/generated/com/partnerd/domain/QCollabInquiry.java
  src/main/generated/com/partnerd/domain/QCollabPost.java
  src/main/generated/com/partnerd/domain/QCommunity.java
  src/main/generated/com/partnerd/domain/QCommunityComment.java
  src/main/generated/com/partnerd/domain/QCommunityImage.java
  src/main/generated/com/partnerd/domain/QContactMethod.java
  src/main/generated/com/partnerd/domain/QEventImage.java
  src/main/generated/com/partnerd/domain/QEventType.java
  src/main/generated/com/partnerd/domain/QMember.java
  src/main/generated/com/partnerd/domain/QPersonal.java
  src/main/generated/com/partnerd/domain/QPersonalLink.java
  src/main/generated/com/partnerd/domain/QProject.java
  src/main/generated/com/partnerd/domain/QProjectComment.java
  src/main/generated/com/partnerd/domain/QProjectImage.java
  src/main/generated/com/partnerd/domain/QProjectRole.java
  src/main/generated/com/partnerd/domain/QPromotionProject.java
  src/main/generated/com/partnerd/domain/QPromotionProjectComment.java
  src/main/generated/com/partnerd/domain/QPromotionProjectImage.java
  src/main/generated/com/partnerd/domain/QPromotionProjectRole.java
  src/main/generated/com/partnerd/domain/common/QBaseEntity.java
  src/main/generated/com/partnerd/domain/mapping/QClubMember.java
  src/main/generated/com/partnerd/domain/mapping/QClubMembershipRequest.java
  src/main/generated/com/partnerd/domain/mapping/QCollabPostCategory.java
  src/main/generated/com/partnerd/domain/mapping/QCollabRequest.java
  src/main/generated/com/partnerd/domain/mapping/QProjectMember.java
  src/main/generated/com/partnerd/domain/mapping/QPromotionProjectMember.java
  src/main/java/com/partnerd/domain/CollabPost.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabPostCommandServiceImpl.java
  src/main/java/com/partnerd/web/dto/collabDTO/request/CollabPostRequestDTO.java
Labels: :recycle: Refactor, :rocket: Chore

#25 [FEAT] 콜라보레이션 글 전체 조회 API 구현
  src/main/java/com/partnerd/converter/collabPostConverter/CollabPostConverter.java
  src/main/java/com/partnerd/domain/CollabInquiry.java
  src/main/java/com/partnerd/domain/CollabPost.java
  src/main/java/com/partnerd/domain/ContactMethod.java
  src/main/java/com/partnerd/domain/EventImage.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepository.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepositoryCustom.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/collabPostService/CollabPostQueryService.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabPostQueryServiceImpl.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostRestController.java
  src/main/java/com/partnerd/web/dto/collabDTO/request/CollabPostRequestDTO.java
  src/main/java/com/partnerd/web/dto/collabDTO/response/CollabPostResponseDTO.java
Labels: :sparkles: Feature, :recycle: Refactor

#27 [FIX] 엔티티 필드명 변경 후 엔티티 필드명 변경 미반영으로 인한 오류 해결
  src/main/java/com/partnerd/service/collabPostService/impl/CollabPostCommandServiceImpl.java
Labels: :bug: Fix

#34 [REFACTOR] Member, Agreements 단방향으로 매핑 수정
  src/main/java/com/partnerd/domain/Agreements.java
  src/main/java/com/partnerd/domain/Member.java
Labels: :recycle: Refactor

#39 [FIX] ContactType칼럼명 변경으로 인한 메서드 수정 및 오류해결(#38)
  src/main/java/com/partnerd/service/clubService/impl/ClubServiceImpl.java
Labels: :bug: Fix

#42 [REFACTOR ] 프로젝트 생성/수정 API 수정(#41)
  src/main/java/com/partnerd/converter/projectConverter/ProjectConverter.java
  src/main/java/com/partnerd/domain/ContactMethod.java
  src/main/java/com/partnerd/domain/Project.java
  src/main/java/com/partnerd/domain/PromotionProject.java
  src/main/java/com/partnerd/service/projectService/ProjectServiceImpl.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectServiceImpl.java
  src/main/java/com/partnerd/web/controller/projectController/PromotionProjectRestController.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectRequestDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectResponseDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectRequestDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectResponseDTO.java
Labels: :sparkles: Feature, :recycle: Refactor

#44 [CI] CI/CD 파이프라인 구축 (#43)
  .github/workflows/dev_deploy.yml
  src/main/java/com/partnerd/config/WebConfig.java
  src/main/java/com/partnerd/config/security/SecurityConfig.java
Labels: :sparkles: Feature, :construction_worker: CI/CD

#46 [FEAT] S3 설정 세팅 (#45)
  build.gradle
  src/main/java/com/partnerd/aws/AmazonS3Manager.java
  src/main/java/com/partnerd/config/AmazonConfig.java
  src/main/java/com/partnerd/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/partnerd/domain/common/Uuid.java
  src/main/java/com/partnerd/repository/uuidRepository/UuidRepository.java
  src/main/resources/application.yml
Labels: ⚙ Setting, :sparkles: Feature

#48 [FEAT] https 적용 (#47)
  src/main/java/com/partnerd/web/controller/healthController/HealthRestController.java
Labels: ⚙ Setting, :sparkles: Feature

#49 [FEAT] 카카오 로그인 API 구현 (#10)
  build.gradle
  src/main/java/com/partnerd/config/RestTemplateConfig.java
  src/main/java/com/partnerd/config/security/JwtAuthenticationFilter.java
  src/main/java/com/partnerd/config/security/JwtTokenProvider.java
  src/main/java/com/partnerd/config/security/SecurityConfig.java
  src/main/java/com/partnerd/converter/AgreementsConverter.java
  src/main/java/com/partnerd/converter/AuthMemberConverter.java
  src/main/java/com/partnerd/domain/Agreements.java
  src/main/java/com/partnerd/domain/Member.java
  src/main/java/com/partnerd/repository/memberRepository/MemberRepository.java
  src/main/java/com/partnerd/service/auth/KakaoOAuthServiceImpl.java
  src/main/java/com/partnerd/service/auth/OAuthService.java
  src/main/java/com/partnerd/service/auth/RegisterService.java
  src/main/java/com/partnerd/service/auth/RegisterServiceImpl.java
  src/main/java/com/partnerd/web/controller/AuthController.java
  src/main/java/com/partnerd/web/dto/authDTO/LoginResponseDTO.java
  src/main/java/com/partnerd/web/dto/oauthDTO/KakaoResponseDTO.java
  src/main/java/com/partnerd/web/dto/registerDTO/AgreementsDTO.java
  src/main/java/com/partnerd/web/dto/registerDTO/RegisterRequestDTO.java
  src/main/java/com/partnerd/web/dto/registerDTO/RegisterResponseDTO.java
  src/main/resources/application.yml
Labels: :sparkles: Feature

#52 [FEAT] 닉네임중복확인 API 구현 (#50)
  src/main/java/com/partnerd/repository/memberRepository/MemberRepository.java
  src/main/java/com/partnerd/service/memberService/MemberService.java
  src/main/java/com/partnerd/service/memberService/MemberServiceImpl.java
  src/main/java/com/partnerd/web/controller/MemberRestController.java
Labels: :sparkles: Feature

#58 [REFACTOR] 카카오 로그인 Refresh token 처리 방식 작성 및 수정 (#53)
  src/main/java/com/partnerd/domain/RefreshToken.java
  src/main/java/com/partnerd/repository/refreshTokenRepository/RefreshTokenRepository.java
  src/main/java/com/partnerd/service/auth/KakaoOAuthServiceImpl.java
  src/main/java/com/partnerd/service/token/TokenService.java
Labels: :recycle: Refactor

#56 [FEAT] 프로젝트 모집글 목록 조회 API 구현 (#18)
  src/main/java/com/partnerd/converter/projectConverter/ProjectConverter.java
  src/main/java/com/partnerd/domain/Project.java
  src/main/java/com/partnerd/domain/enums/ProjectStatus.java
  src/main/java/com/partnerd/service/projectService/ProjectService.java
  src/main/java/com/partnerd/service/projectService/ProjectServiceImpl.java
  src/main/java/com/partnerd/web/controller/projectController/ProjectRestController.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectCategoryDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectRequestDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectResponseDTO.java
Labels: :sparkles: Feature

#65 [FIX] Swagger 설정 (#64)
  src/main/java/com/partnerd/web/controller/AuthController.java
Labels: :bug: Fix

#63 [FEAT] 홈화면 동아리/콜라보레이션/프로젝트 조회 API 구현
  src/main/java/com/partnerd/domain/Club.java
  src/main/java/com/partnerd/domain/PromotionProject.java
  src/main/java/com/partnerd/repository/clubRepository/ClubRepository.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepository.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectRepository.java
  src/main/java/com/partnerd/repository/projectRepository/PromotionProjectRepository.java
  src/main/java/com/partnerd/service/homeService/HomeService.java
  src/main/java/com/partnerd/service/homeService/impl/HomeServiceImpl.java
  src/main/java/com/partnerd/web/controller/HomeController.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubRegisterRequestDTO.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubUpdateRequestDTO.java
  src/main/java/com/partnerd/web/dto/homeDTO/response/HomeClubDTO.java
  src/main/java/com/partnerd/web/dto/homeDTO/response/HomeCollabPostDTO.java
  src/main/java/com/partnerd/web/dto/homeDTO/response/HomeProjectDTO.java
  src/main/java/com/partnerd/web/dto/homeDTO/response/HomePromotionProjectDTO.java
  src/main/java/com/partnerd/web/dto/homeDTO/response/HomeResponseDTO.java
Labels: :sparkles: Feature

#60 [FEAT] 콜라보레이션 문의글 및 답변 작성/수정/삭제 API 구현
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/apiPaylaod/exception/handler/CollabInquiryHandler.java
  src/main/java/com/partnerd/converter/collabPostConverter/CollabInquiryConverter.java
  src/main/java/com/partnerd/domain/CollabInquiry.java
  src/main/java/com/partnerd/domain/CollabPost.java
  src/main/java/com/partnerd/domain/Member.java
  src/main/java/com/partnerd/domain/enums/CollabInquiryStatus.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabInquiryRepository.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabInquiryRepositoryCustom.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabInquiryRepositoryCustomImpl.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepository.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepositoryCustom.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/collabPostService/CollabInquiryCommandService.java
  src/main/java/com/partnerd/service/collabPostService/CollabInquiryQueryService.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabInquiryCommandServiceImpl.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabInquiryQueryServiceImpl.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostInquiryRestController.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostRestController.java
  src/main/java/com/partnerd/web/dto/collabDTO/request/CollabInquiryRequestDTO.java
  src/main/java/com/partnerd/web/dto/collabDTO/response/CollabInquiryResponseDTO.java
Labels: :sparkles: Feature, :recycle: Refactor

#59 [FEAT] 콜라보레이션 글 상세 조회 API 구현
  src/main/java/com/partnerd/converter/collabPostConverter/CollabPostConverter.java
  src/main/java/com/partnerd/domain/CollabInquiry.java
  src/main/java/com/partnerd/domain/CollabPost.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepositoryCustom.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/collabPostService/CollabPostQueryService.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabPostQueryServiceImpl.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostInquiryRestController.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostRestController.java
  src/main/java/com/partnerd/web/dto/collabDTO/response/CollabInquiryResponseDTO.java
  src/main/java/com/partnerd/web/dto/collabDTO/response/CollabPostResponseDTO.java
  src/main/java/com/partnerd/web/dto/contactMethodDTO/ContactMethodDTO.java
Labels: :sparkles: Feature

#61 [FEAT] 카테고리 별 콜라보레이션 글 목록 조회 API 구현
  src/main/java/com/partnerd/converter/collabPostConverter/CollabPostConverter.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepositoryCustom.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/collabPostService/CollabPostQueryService.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabPostQueryServiceImpl.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostRestController.java
  src/main/java/com/partnerd/web/dto/collabDTO/response/CollabPostResponseDTO.java
Labels: :sparkles: Feature, :recycle: Refactor

#66 [FEAT] 프로젝트 홍보글 목록 조회 API 구현 (#57)
  src/main/java/com/partnerd/converter/projectConverter/PromotionProjectConverter.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectService.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectServiceImpl.java
  src/main/java/com/partnerd/web/controller/projectController/PromotionProjectRestController.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectRequestDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectResponseDTO.java
Labels: :sparkles: Feature

#69 [FEAT] 파트너드 찾기 전체 목록 조회 API구현(페이징)
  src/main/java/com/partnerd/converter/ClubConverter.java
  src/main/java/com/partnerd/domain/Club.java
  src/main/java/com/partnerd/repository/clubRepository/ClubRepository.java
  src/main/java/com/partnerd/service/clubService/ClubService.java
  src/main/java/com/partnerd/service/clubService/impl/ClubServiceImpl.java
  src/main/java/com/partnerd/web/controller/ClubRestController.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubDTO.java
Labels: :sparkles: Feature

#71 [FEAT] 프로젝트 모집글 상세페이지 조회 API 구현 (#67)
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/converter/projectConverter/ProjectCategoryPreferConverter.java
  src/main/java/com/partnerd/converter/projectConverter/ProjectConverter.java
  src/main/java/com/partnerd/converter/projectConverter/ProjectMemberConverter.java
  src/main/java/com/partnerd/domain/CollabPost.java
  src/main/java/com/partnerd/domain/ContactMethod.java
  src/main/java/com/partnerd/domain/Project.java
  src/main/java/com/partnerd/domain/ProjectCategory.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectRepositoryCustiom.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectRepositoryImpl.java
  src/main/java/com/partnerd/service/projectService/ProjectService.java
  src/main/java/com/partnerd/service/projectService/ProjectServiceImpl.java
  src/main/java/com/partnerd/web/controller/projectController/ProjectRestController.java
  src/main/java/com/partnerd/web/dto/contactMethodDTO/ContactMethodDTO.java
  src/main/java/com/partnerd/web/dto/memberDTO/MemberResponseDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectMemberDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectRequestDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectResponseDTO.java
Labels: :sparkles: Feature

#73 [FEAT] 프로젝트 홍보글 상세페이지 조회 API 구현 (#72)
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/converter/projectConverter/PromotionProjectConverter.java
  src/main/java/com/partnerd/converter/projectConverter/PromotionProjectMemberConverter.java
  src/main/java/com/partnerd/domain/ContactMethod.java
  src/main/java/com/partnerd/domain/PromotionProject.java
  src/main/java/com/partnerd/repository/projectRepository/PromotionProjectRepositoryCustiom.java
  src/main/java/com/partnerd/repository/projectRepository/PromotionProjectRepositoryImpl.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectService.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectServiceImpl.java
  src/main/java/com/partnerd/web/controller/projectController/PromotionProjectRestController.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectMemberDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectRequestDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectResponseDTO.java
Labels: :sparkles: Feature

#78 [REFACTOR] AuthController 에러 핸들러 수정 (#68)
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/apiPaylaod/exception/handler/AuthHandler.java
  src/main/java/com/partnerd/apiPaylaod/exception/handler/RegisterHandler.java
  src/main/java/com/partnerd/service/auth/KakaoOAuthServiceImpl.java
  src/main/java/com/partnerd/service/auth/RegisterServiceImpl.java
  src/main/java/com/partnerd/web/controller/AuthController.java
Labels: :recycle: Refactor

#81 [REFACTOR] 파트너드 등록시 동아리장 권한 부여 수정
  src/main/java/com/partnerd/converter/ClubConverter.java
  src/main/java/com/partnerd/repository/clubMemberRepository/ClubMemberRepository.java
  src/main/java/com/partnerd/service/clubService/ClubService.java
  src/main/java/com/partnerd/service/clubService/impl/ClubServiceImpl.java
  src/main/java/com/partnerd/web/controller/ClubRestController.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubUpdateRequestDTO.java
Labels: :recycle: Refactor

#86 [FEAT] 마이페이지 팀페이지(파트너드) 목록 조회 API 구현
  src/main/java/com/partnerd/converter/ClubConverter.java
  src/main/java/com/partnerd/repository/clubMemberRepository/ClubMemberRepository.java
  src/main/java/com/partnerd/service/clubService/ClubService.java
  src/main/java/com/partnerd/service/clubService/impl/ClubServiceImpl.java
  src/main/java/com/partnerd/web/controller/ClubRestController.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubResponseDTO.java
Labels: :sparkles: Feature

#84 [FEAT] 콜라보 요청/조회/취소 API 구현
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/apiPaylaod/exception/handler/CollabAskHandler.java
  src/main/java/com/partnerd/converter/collabAskConverter/CollabAskConverter.java
  src/main/java/com/partnerd/domain/Member.java
  src/main/java/com/partnerd/domain/mapping/ClubMember.java
  src/main/java/com/partnerd/domain/mapping/CollabAsk.java
  src/main/java/com/partnerd/domain/mapping/CollabRequest.java
  src/main/java/com/partnerd/repository/clubMemberRepository/ClubMemberRepository.java
  src/main/java/com/partnerd/repository/collabAskRepository/CollabAskRepository.java
  src/main/java/com/partnerd/repository/collabAskRepository/CollabAskRepositoryCustom.java
  src/main/java/com/partnerd/repository/collabAskRepository/CollabAskRepositoryCustomImpl.java
  src/main/java/com/partnerd/repository/memberRepository/MemberRepository.java
  src/main/java/com/partnerd/service/collabRequestService/CollabAskCommandService.java
  src/main/java/com/partnerd/service/collabRequestService/CollabAskQueryService.java
  src/main/java/com/partnerd/service/collabRequestService/impl/CollabAskCommandServiceImpl.java
  src/main/java/com/partnerd/service/collabRequestService/impl/CollabAskQueryServiceImpl.java
  src/main/java/com/partnerd/web/controller/collabAskController/CollabAskRestController.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostRestController.java
  src/main/java/com/partnerd/web/dto/collabDTO/request/CollabAskRequestDTO.java
  src/main/java/com/partnerd/web/dto/collabDTO/response/CollabAskResponseDTO.java
Labels: :sparkles: Feature

#85 [FEAT] 콜라보 문의글 및 답변글 좋아요/좋아요 취소 API 구현
  src/main/java/com/partnerd/domain/CollabInquiry.java
  src/main/java/com/partnerd/service/collabPostService/CollabInquiryCommandService.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabInquiryCommandServiceImpl.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostInquiryRestController.java
Labels: :sparkles: Feature

#91 [FEAT] 마이페이지-내가 쓴 글(콜라보레이션/프로젝트모집/프로젝트홍보) 목록 조회 API 구현
  src/main/java/com/partnerd/converter/collabPostConverter/CollabPostConverter.java
  src/main/java/com/partnerd/converter/projectConverter/ProjectConverter.java
  src/main/java/com/partnerd/converter/projectConverter/PromotionProjectConverter.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepositoryCustom.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepositoryCustomImpl.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectRepositoryCustiom.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectRepositoryImpl.java
  src/main/java/com/partnerd/repository/projectRepository/PromotionProjectRepositoryCustiom.java
  src/main/java/com/partnerd/repository/projectRepository/PromotionProjectRepositoryImpl.java
  src/main/java/com/partnerd/service/collabPostService/CollabPostQueryService.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabPostQueryServiceImpl.java
  src/main/java/com/partnerd/service/projectService/ProjectService.java
  src/main/java/com/partnerd/service/projectService/ProjectServiceImpl.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectService.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectServiceImpl.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostRestController.java
  src/main/java/com/partnerd/web/controller/projectController/ProjectRestController.java
  src/main/java/com/partnerd/web/controller/projectController/PromotionProjectRestController.java
  src/main/java/com/partnerd/web/dto/collabDTO/response/CollabPostResponseDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectResponseDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectResponseDTO.java
Labels: :sparkles: Feature, :recycle: Refactor

#94 [FEAT] JWT 토큰 갱신 API 구현 (#62)
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/apiPaylaod/exception/handler/TokenHandler.java
  src/main/java/com/partnerd/config/security/JwtTokenProvider.java
  src/main/java/com/partnerd/config/security/SecurityConfig.java
  src/main/java/com/partnerd/domain/RefreshToken.java
  src/main/java/com/partnerd/service/auth/TokenManagementService.java
  src/main/java/com/partnerd/service/token/TokenService.java
  src/main/java/com/partnerd/web/controller/AuthController.java
  src/main/java/com/partnerd/web/dto/authDTO/TokenRefreshRequestDTO.java
  src/main/java/com/partnerd/web/dto/authDTO/TokenRefreshResponseDTO.java
  src/main/resources/application.yml
Labels: :sparkles: Feature

#96 [REFACTOR] 카카오 로그인, register api의 error status 세분화 (#95)
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/service/auth/KakaoOAuthServiceImpl.java
  src/main/java/com/partnerd/service/auth/RegisterServiceImpl.java
Labels: :recycle: Refactor

#92 [REFACTOR] 중복 요청/작성자 요청 제한 로직 추가 및 Club 데이터 즉시 조회를 위한 쿼리 수정
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/config/security/SecurityConfig.java
  src/main/java/com/partnerd/domain/mapping/CollabAsk.java
  src/main/java/com/partnerd/repository/clubMemberRepository/ClubMemberRepository.java
  src/main/java/com/partnerd/repository/collabAskRepository/CollabAskRepository.java
  src/main/java/com/partnerd/repository/collabAskRepository/CollabAskRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/collabAskService/CollabAskCommandService.java
  src/main/java/com/partnerd/service/collabAskService/impl/CollabAskCommandServiceImpl.java
  src/main/java/com/partnerd/web/controller/collabAskController/CollabAskRestController.java
Labels: :sparkles: Feature, :recycle: Refactor

#98 [REFACTOR] 카카오 로그인 API 응답 수정 (#97)
  src/main/java/com/partnerd/service/auth/KakaoOAuthServiceImpl.java
  src/main/java/com/partnerd/web/dto/authDTO/LoginResponseDTO.java
Labels: :recycle: Refactor

#104 [REFACTOR] 콜라보 전체 조회 (카테고리 별 포함) 쿼리 수정
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepositoryCustomImpl.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostRestController.java
Labels: :recycle: Refactor

#105 [REFACTOR] 콜라보 글 생성 쿼리에서 불필요한 IN절 제거를 위해 쿼리 수정
  src/main/java/com/partnerd/repository/categoryRepository/CategoryRepository.java
  src/main/java/com/partnerd/repository/categoryRepository/CategoryRepositoryCustom.java
  src/main/java/com/partnerd/repository/categoryRepository/CategoryRepositoryImpl.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabPostCommandServiceImpl.java
Labels: :recycle: Refactor

#106 [REFACTOR] 콜라보 글과 콜라보 요청 연관관계 양방향매핑
  src/main/java/com/partnerd/domain/CollabPost.java
  src/main/java/com/partnerd/repository/collabPostRepository/EventTypeRepository.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabPostQueryServiceImpl.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostRestController.java
Labels: :recycle: Refactor

#109 [FEAT] 프로젝트 모집글 댓글(대댓글) CRUD API 구현 (#74)
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/converter/projectConverter/ProjectCommentConverter.java
  src/main/java/com/partnerd/domain/Member.java
  src/main/java/com/partnerd/domain/Project.java
  src/main/java/com/partnerd/domain/ProjectComment.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectCommentRepository.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectCommentRepositoryCustom.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectCommentRepositoryImpl.java
  src/main/java/com/partnerd/service/projectService/ProjectCommentService.java
  src/main/java/com/partnerd/service/projectService/ProjectCommentServiceImpl.java
  src/main/java/com/partnerd/web/controller/projectController/ProjectCommentRestController.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectCommentRequestDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectCommentResponseDTO.java
Labels: :sparkles: Feature

#108 [FEAT] 콜라보 글 생성 시 동아리 리더진 확인 로직 추가 및 로그인 한 사용자 아이디 추출 방식 추가
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/converter/collabPostConverter/CollabPostConverter.java
  src/main/java/com/partnerd/domain/CollabPost.java
  src/main/java/com/partnerd/repository/clubMemberRepository/ClubMemberRepository.java
  src/main/java/com/partnerd/service/collabPostService/CollabPostCommandService.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabPostCommandServiceImpl.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostRestController.java
Labels: :sparkles: Feature, :recycle: Refactor

#115 [FEAT] 파트너드(동아리) 가입 요청 승인/거부 API 구현
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/apiPaylaod/exception/handler/ClubMembershipRequestHandler.java
  src/main/java/com/partnerd/converter/ClubMembershipRequestConverter.java
  src/main/java/com/partnerd/domain/Club.java
  src/main/java/com/partnerd/domain/Member.java
  src/main/java/com/partnerd/domain/mapping/ClubMembershipRequest.java
  src/main/java/com/partnerd/repository/clubMemberRepository/ClubMemberRepositoryCustom.java
  src/main/java/com/partnerd/repository/clubMemberRepository/ClubMemberRepositoryCustomImpl.java
  src/main/java/com/partnerd/repository/clubMembershipRequestRepository/ClubMembershipRequestRepository.java
  src/main/java/com/partnerd/repository/clubMembershipRequestRepository/ClubMembershipRequestRepositoryCustom.java
  src/main/java/com/partnerd/repository/clubMembershipRequestRepository/ClubMembershipRequestRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/clubMembershipRequestService/ClubMembershipRequestService.java
  src/main/java/com/partnerd/service/clubMembershipRequestService/ClubMembershipRequestServiceImpl.java
  src/main/java/com/partnerd/web/controller/ClubMembershipRequestRestController.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubRequestDTO.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubResponseDTO.java
Labels: :sparkles: Feature

#114 [REFACTOR] 콜라보 로그인 사용자 인증 및 아이디 추출 방식 리팩토링
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/domain/CollabInquiry.java
  src/main/java/com/partnerd/domain/CollabPost.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabInquiryRepository.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepository.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/collabPostService/CollabInquiryCommandService.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabInquiryCommandServiceImpl.java
  src/main/java/com/partnerd/web/controller/NotifyController/NotifyController.java
  src/main/java/com/partnerd/web/controller/collabAskController/CollabAskRestController.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostInquiryRestController.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostRestController.java
  src/main/java/com/partnerd/web/dto/collabDTO/response/CollabPostResponseDTO.java
Labels: :recycle: Refactor

#119 [FEAT] 파트너드(동아리) 리더 권한 위임
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/converter/clubConverter/ClubConverter.java
  src/main/java/com/partnerd/converter/clubConverter/ClubMemberConverter.java
  src/main/java/com/partnerd/converter/clubConverter/ClubMembershipRequestConverter.java
  src/main/java/com/partnerd/domain/mapping/ClubMember.java
  src/main/java/com/partnerd/service/clubMemberService/ClubMemberService.java
  src/main/java/com/partnerd/service/clubMemberService/ClubMemberServiceImpl.java
  src/main/java/com/partnerd/service/clubService/impl/ClubServiceImpl.java
  src/main/java/com/partnerd/web/controller/clubController/ClubMemberRestController.java
  src/main/java/com/partnerd/web/controller/clubController/ClubMembershipRequestRestController.java
  src/main/java/com/partnerd/web/controller/clubController/ClubRestController.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubMemberResponseDTO.java
Labels: :sparkles: Feature, :label: Rename

#123 [FEAT] 파트너드(동아리) 가입 요청 API 구현
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/converter/clubConverter/ClubMembershipRequestConverter.java
  src/main/java/com/partnerd/service/clubMembershipRequestService/ClubMembershipRequestService.java
  src/main/java/com/partnerd/service/clubMembershipRequestService/ClubMembershipRequestServiceImpl.java
  src/main/java/com/partnerd/web/controller/clubController/ClubMembershipRequestRestController.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubResponseDTO.java
Labels: :sparkles: Feature

#125 [CI/CD] 스프링부트 도커로 배포 방식 변경
  .github/workflows/dev_deploy.yml
  DockerFile
Labels: :construction_worker: CI/CD

#126 [FIX] 도커파일 DockerFile -> Dockerfile 로 이름 변경
  Dockerfile
Labels: :bug: Fix

#127 [FIX] docker-compose.yml 경로 명시
  .github/workflows/dev_deploy.yml
Labels: :bug: Fix

#128 [FIX] docker-compose 명령어 -f 제거
  .github/workflows/dev_deploy.yml
Labels: :bug: Fix

#129 [FEAT] Kafka, MongoDB 설정 및 Kafka 채팅 기능 구현 v1
  build.gradle
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/config/AsyncConfig.java
  src/main/java/com/partnerd/config/MongoDBConfig.java
  src/main/java/com/partnerd/config/RedisConfig.java
  src/main/java/com/partnerd/config/WebsocketConfig.java
  src/main/java/com/partnerd/config/kafka/KafkaConsumerConfig.java
  src/main/java/com/partnerd/config/kafka/KafkaProducerConfig.java
  src/main/java/com/partnerd/domain/chat/Chatting.java
  src/main/java/com/partnerd/kafka/KafkaConsumer.java
  src/main/java/com/partnerd/kafka/KafkaProducer.java
  src/main/java/com/partnerd/kafka/Message.java
  src/main/java/com/partnerd/service/notifyService/NotificationService.java
  src/main/java/com/partnerd/web/controller/chatController/ChatController.java
  src/main/java/com/partnerd/web/dto/chatDTO/ChatDTO.java
  src/main/java/com/partnerd/web/dto/collabDTO/request/CollabInquiryRequestDTO.java
  src/main/resources/application.yml
Labels: ⚙ Setting, :sparkles: Feature

#130 [FIX] redis value 값 경로 오타 수정
  src/main/java/com/partnerd/config/RedisConfig.java
Labels: :bug: Fix

#131 [FIX] redisconfig 임시 삭제
  src/main/java/com/partnerd/config/RedisConfig.java
Labels: :bug: Fix

#134 [REFACTOR] 프로젝트 이미지 적용 (#113)
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/converter/projectConverter/ProjectCommentConverter.java
  src/main/java/com/partnerd/converter/projectConverter/ProjectConverter.java
  src/main/java/com/partnerd/converter/projectConverter/PromotionProjectCommentConverter.java
  src/main/java/com/partnerd/converter/projectConverter/PromotionProjectConverter.java
  src/main/java/com/partnerd/domain/Project.java
  src/main/java/com/partnerd/domain/ProjectImage.java
  src/main/java/com/partnerd/domain/PromotionProject.java
  src/main/java/com/partnerd/domain/PromotionProjectImage.java
  src/main/java/com/partnerd/domain/enums/ImageType.java
  src/main/java/com/partnerd/service/projectService/ProjectServiceImpl.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectServiceImpl.java
  src/main/java/com/partnerd/service/s3Service/S3Service.java
  src/main/java/com/partnerd/web/controller/projectController/ProjectRestController.java
  src/main/java/com/partnerd/web/controller/projectController/PromotionProjectRestController.java
  src/main/java/com/partnerd/web/dto/memberDTO/MemberResponseDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectMemberDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectRequestDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectResponseDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectMemberDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectRequestDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectResponseDTO.java
Labels: :recycle: Refactor

#138 [CI/CD] redisconfig 추가
  src/main/java/com/partnerd/config/RedisConfig.java
Labels: :bug: Fix, :construction_worker: CI/CD

#140 fix: 레디스 경로 설정 수정
  src/main/resources/application.yml
Labels: :bug: Fix, :construction_worker: CI/CD

#145 Fix: Redis config 수정
  src/main/java/com/partnerd/config/RedisConfig.java
Labels: :bug: Fix

#147 Fix: lettuce-core의 Gradle 의존성 추가
  build.gradle
Labels: :bug: Fix, :construction_worker: CI/CD

#148 Fix: lettuce-core의 Gradle 의존성 변경
  build.gradle
Labels: :bug: Fix, :construction_worker: CI/CD

#149 Fix: deploy.yml 수정
  .github/workflows/dev_deploy.yml
Labels: :bug: Fix, :construction_worker: CI/CD
