Repository UMC-partNerd/backend, pull requests merged in 2025-02, with the labels that each got.

#150 [REFACTOR] 파트너드 이미지 적용
  src/main/java/com/partnerd/converter/clubConverter/ClubConverter.java
  src/main/java/com/partnerd/domain/Club.java
  src/main/java/com/partnerd/domain/ClubActivity.java
  src/main/java/com/partnerd/domain/ClubActivityImage.java
  src/main/java/com/partnerd/domain/ClubImage.java
  src/main/java/com/partnerd/domain/ContactMethod.java
  src/main/java/com/partnerd/repository/clubRepository/ClubActivityImageRepository.java
  src/main/java/com/partnerd/repository/clubRepository/ClubActivityRepository.java
  src/main/java/com/partnerd/service/clubService/ClubService.java
  src/main/java/com/partnerd/service/clubService/impl/ClubServiceImpl.java
  src/main/java/com/partnerd/web/controller/clubController/ClubRestController.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubActivityDTO.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubDTO.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubRegisterRequestDTO.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubUpdateRequestDTO.java
Labels: :recycle: Refactor

#152 [FEAT] 프로젝트 팀원 검색 API 구현 (#135)
  src/main/java/com/partnerd/config/RedisConfig.java
  src/main/java/com/partnerd/converter/projectConverter/ProjectConverter.java
  src/main/java/com/partnerd/converter/projectConverter/PromotionProjectConverter.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectRepositoryCustiom.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectRepositoryImpl.java
  src/main/java/com/partnerd/service/projectService/ProjectService.java
  src/main/java/com/partnerd/service/projectService/ProjectServiceImpl.java
  src/main/java/com/partnerd/web/controller/projectController/ProjectRestController.java
  src/main/java/com/partnerd/web/dto/memberDTO/MemberResponseDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectMemberDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectRequestDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectMemberDTO.java
Labels: :sparkles: Feature

#154 [Refactor] 카카오 로그인 응답 수정 (#153)
  src/main/java/com/partnerd/service/auth/KakaoOAuthServiceImpl.java
  src/main/java/com/partnerd/web/dto/authDTO/LoginResponseDTO.java
Labels: :recycle: Refactor

#155 [FIX] swagger url 변경
  src/main/java/com/partnerd/config/SwaggerConfig.java
  src/main/java/com/partnerd/service/auth/KakaoOAuthServiceImpl.java
  src/main/resources/application.yml
Labels: :bug: Fix, :construction_worker: CI/CD

#159 [REFACTOR] 홈화면 조회 API 이미지로직 리팩토링
  src/main/java/com/partnerd/repository/clubRepository/ClubRepository.java
  src/main/java/com/partnerd/repository/clubRepository/ClubRepositoryCustom.java
  src/main/java/com/partnerd/repository/clubRepository/ClubRepositoryCustomImpl.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepositoryCustom.java
  src/main/java/com/partnerd/repository/collabPostRepository/CollabPostRepositoryCustomImpl.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectRepositoryCustiom.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectRepositoryImpl.java
  src/main/java/com/partnerd/repository/projectRepository/PromotionProjectRepositoryCustiom.java
  src/main/java/com/partnerd/repository/projectRepository/PromotionProjectRepositoryImpl.java
  src/main/java/com/partnerd/service/homeService/impl/HomeServiceImpl.java
  src/main/java/com/partnerd/web/dto/homeDTO/response/HomeClubDTO.java
  src/main/java/com/partnerd/web/dto/homeDTO/response/HomeCollabPostDTO.java
Labels: :recycle: Refactor

#161 [FEAT] 기본 프로필 이미지 추가 (#156)
  src/main/java/com/partnerd/service/auth/RegisterServiceImpl.java
Labels: :sparkles: Feature

#163 [REFACTOR] 마이페이지 팀페이지(파트너드) 목록 조회 API 수정
  src/main/java/com/partnerd/converter/clubConverter/ClubConverter.java
  src/main/java/com/partnerd/domain/Club.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubResponseDTO.java
Labels: :recycle: Refactor

#165 [REFACTOR] 마이페이지-내프로필 이미지 등록/조회
  src/main/java/com/partnerd/converter/MemberConverter.java
  src/main/java/com/partnerd/domain/enums/ImageType.java
  src/main/java/com/partnerd/service/memberService/MemberServiceImpl.java
  src/main/java/com/partnerd/service/s3Service/S3Service.java
  src/main/java/com/partnerd/web/dto/memberDTO/MemberRequestDTO.java
  src/main/java/com/partnerd/web/dto/memberDTO/MemberResponseDTO.java
Labels: :recycle: Refactor

#167 [REFACTOR] 퍼스널페이지 조회 api 수정
  src/main/java/com/partnerd/converter/PersonalConverter.java
  src/main/java/com/partnerd/web/dto/personalDTO/PersonalResponseDTO.java
Labels: :recycle: Refactor

#168 [REFACTOR] 프로젝트 프로필 이미지 적용 (#162)
  src/main/java/com/partnerd/config/SwaggerConfig.java
  src/main/java/com/partnerd/converter/projectConverter/ProjectCommentConverter.java
  src/main/java/com/partnerd/converter/projectConverter/ProjectConverter.java
  src/main/java/com/partnerd/converter/projectConverter/PromotionProjectCommentConverter.java
  src/main/java/com/partnerd/converter/projectConverter/PromotionProjectConverter.java
  src/main/java/com/partnerd/web/dto/memberDTO/MemberResponseDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectCommentResponseDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectMemberDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectCommentResponseDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectMemberDTO.java
Labels: :recycle: Refactor

#169 [REFACTOR ] 파트너드 조회 API 수정(카테고리id, clubId)
  src/main/java/com/partnerd/converter/clubConverter/ClubConverter.java
  src/main/java/com/partnerd/repository/clubRepository/ClubRepositoryCustom.java
  src/main/java/com/partnerd/repository/clubRepository/ClubRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/clubService/impl/ClubServiceImpl.java
  src/main/java/com/partnerd/web/controller/clubController/ClubRestController.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubDTO.java
Labels: :recycle: Refactor

#172 [FEAT] 파트너드(동아리) 회원 관리 API 구현
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/converter/clubConverter/ClubMemberConverter.java
  src/main/java/com/partnerd/service/clubMemberService/ClubMemberService.java
  src/main/java/com/partnerd/service/clubMemberService/ClubMemberServiceImpl.java
  src/main/java/com/partnerd/web/controller/clubController/ClubMemberRestController.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubMemberResponseDTO.java
Labels: :sparkles: Feature

#171 [FEAT]파트너드 상세 조회(팀페이지) API 구현
  src/main/java/com/partnerd/repository/clubRepository/ClubRepositoryCustom.java
  src/main/java/com/partnerd/repository/clubRepository/ClubRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/clubService/ClubService.java
  src/main/java/com/partnerd/service/clubService/impl/ClubServiceImpl.java
  src/main/java/com/partnerd/web/controller/clubController/ClubRestController.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubActivityDTO.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubDetailCollabDTO.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubDetailMemberDTO.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubDetailResponseDTO.java
  src/main/java/com/partnerd/web/dto/contactMethodDTO/ContactMethodDTO.java
Labels: :sparkles: Feature

#174 [REFACTOR] 마이페이지-내프로필 조회/수정 API 수정
  src/main/java/com/partnerd/web/controller/MemberRestController.java
Labels: :recycle: Refactor

#177 [REFACTOR] 카카오 로그인 시 redirect uri 동적으로 설정 (#176)
  src/main/java/com/partnerd/service/auth/KakaoOAuthServiceImpl.java
Labels: :recycle: Refactor

#179 [FEAT] 파트너드(동아리) 가입 요청 목록 조회 API 구현
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/converter/clubConverter/ClubMembershipRequestConverter.java
  src/main/java/com/partnerd/repository/clubMembershipRequestRepository/ClubMembershipRequestRepositoryCustom.java
  src/main/java/com/partnerd/repository/clubMembershipRequestRepository/ClubMembershipRequestRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/clubMembershipRequestService/ClubMembershipRequestService.java
  src/main/java/com/partnerd/service/clubMembershipRequestService/ClubMembershipRequestServiceImpl.java
  src/main/java/com/partnerd/web/controller/clubController/ClubMembershipRequestRestController.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubResponseDTO.java
Labels: :sparkles: Feature

#181 [REFACTOR] 파트너드 리더 권한과 요청 목록 보기 관련 코드 수정
  src/main/java/com/partnerd/service/clubMemberService/ClubMemberServiceImpl.java
  src/main/java/com/partnerd/service/clubMembershipRequestService/ClubMembershipRequestServiceImpl.java
Labels: :recycle: Refactor

#184 [FIX] 내가 쓴 글 모아보기 - 프로젝트 관련 수정
  src/main/java/com/partnerd/repository/projectRepository/ProjectRepositoryImpl.java
  src/main/java/com/partnerd/repository/projectRepository/PromotionProjectRepositoryImpl.java
Labels: :bug: Fix

#185 [FEAT] 퍼스널페이지 등록한 홍보 프로젝트 목록 조회 API 구현
  src/main/java/com/partnerd/repository/projectRepository/PromotionProjectRepositoryCustiom.java
  src/main/java/com/partnerd/repository/projectRepository/PromotionProjectRepositoryImpl.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectService.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectServiceImpl.java
  src/main/java/com/partnerd/web/controller/projectController/PromotionProjectRestController.java
Labels: :sparkles: Feature

#186 [FEAT] 프로젝트 댓글 좋아요 API 구현 (#120)
  src/main/java/com/partnerd/domain/ProjectComment.java
  src/main/java/com/partnerd/domain/PromotionProjectComment.java
  src/main/java/com/partnerd/domain/mapping/ProjectLikes.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectLikesRepository.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectLikesRepositoryCustom.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectLikesRepositoryImpl.java
  src/main/java/com/partnerd/service/projectService/ProjectCommentService.java
  src/main/java/com/partnerd/service/projectService/ProjectCommentServiceImpl.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectCommentService.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectCommentServiceImpl.java
  src/main/java/com/partnerd/web/controller/projectController/ProjectCommentRestController.java
  src/main/java/com/partnerd/web/controller/projectController/PromotionProjectCommentRestController.java
  src/main/java/com/partnerd/web/dto/projectDTO/ProjectCommentResponseDTO.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectCommentResponseDTO.java
Labels: :sparkles: Feature

#188 [CI/CD] github action 파일 docker swarm 배포 방식으로 변경
  .github/workflows/dev_deploy.yml
Labels: :construction_worker: CI/CD

#189 [FEAT] 프로젝트 홍보글 투표하기 API 구현 (#121)
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/domain/mapping/ProjectVote.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectVoteRepository.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectVoteRepositoryCustom.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectVoteRepositoryImpl.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectService.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectServiceImpl.java
  src/main/java/com/partnerd/web/controller/projectController/PromotionProjectRestController.java
Labels: :sparkles: Feature

#193 [FEAT] 채팅방 생성 및 조회 API 구현
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/apiPaylaod/exception/handler/ChatRoomHandler.java
  src/main/java/com/partnerd/config/kafka/KafkaProducerConfig.java
  src/main/java/com/partnerd/domain/ChatRoom.java
  src/main/java/com/partnerd/domain/ClubActivity.java
  src/main/java/com/partnerd/domain/ClubActivityImage.java
  src/main/java/com/partnerd/domain/Member.java
  src/main/java/com/partnerd/domain/ProjectComment.java
  src/main/java/com/partnerd/domain/enums/ChatRoomStatus.java
  src/main/java/com/partnerd/domain/enums/ChatRoomType.java
  src/main/java/com/partnerd/domain/mapping/ChatRoomMember.java
  src/main/java/com/partnerd/repository/chatRoomRepository/chatRoom/ChatRoomRepository.java
  src/main/java/com/partnerd/repository/chatRoomRepository/chatRoom/ChatRoomRepositoryCustom.java
  src/main/java/com/partnerd/repository/chatRoomRepository/chatRoom/ChatRoomRepositoryCustomImpl.java
  src/main/java/com/partnerd/repository/chatRoomRepository/chatRoomMember/ChatRoomMemberRepository.java
  src/main/java/com/partnerd/repository/chatRoomRepository/chatRoomMember/ChatRoomMemberRepositoryCustom.java
  src/main/java/com/partnerd/repository/chatRoomRepository/chatRoomMember/ChatRoomMemberRepositoryCustomImpl.java
  src/main/java/com/partnerd/repository/clubRepository/ClubRepositoryCustomImpl.java
  src/main/java/com/partnerd/repository/collabAskRepository/CollabAskRepository.java
  src/main/java/com/partnerd/repository/collabAskRepository/CollabAskRepositoryCustom.java
  src/main/java/com/partnerd/repository/collabAskRepository/CollabAskRepositoryCustomImpl.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabInquiry/CollabInquiryRepository.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabInquiry/CollabInquiryRepositoryCustom.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabInquiry/CollabInquiryRepositoryCustomImpl.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabPost/CollabPostCategoryRepository.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabPost/CollabPostImgRepository.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabPost/CollabPostRepository.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabPost/CollabPostRepositoryCustom.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabPost/CollabPostRepositoryCustomImpl.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabPost/EventTypeRepository.java
  src/main/java/com/partnerd/repository/memberRepository/MemberRepository.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectLikesRepositoryCustom.java
  src/main/java/com/partnerd/service/chatRoomService/ChatRoomCommandService.java
  src/main/java/com/partnerd/service/chatRoomService/ChatRoomQueryService.java
  src/main/java/com/partnerd/service/chatRoomService/impl/ChatRoomCommandServiceImpl.java
  src/main/java/com/partnerd/service/chatRoomService/impl/ChatRoomQueryServiceImpl.java
  src/main/java/com/partnerd/service/collabAskService/impl/CollabAskCommandServiceImpl.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabInquiryCommandServiceImpl.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabPostCommandServiceImpl.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabPostQueryServiceImpl.java
  src/main/java/com/partnerd/service/eventTypeService/impl/EventTypeServiceImpl.java
  src/main/java/com/partnerd/service/homeService/impl/HomeServiceImpl.java
  src/main/java/com/partnerd/service/kafkaService/KafkaConsumer.java
  src/main/java/com/partnerd/service/kafkaService/KafkaProducer.java
  src/main/java/com/partnerd/service/kafkaService/Message.java
  src/main/java/com/partnerd/service/s3Service/S3Service.java
  src/main/java/com/partnerd/web/controller/chatController/ChatController.java
  src/main/java/com/partnerd/web/controller/chatController/ChatRoomRestController.java
  src/main/java/com/partnerd/web/controller/collabAskController/CollabAskRestController.java
  src/main/java/com/partnerd/web/dto/chatRoomDTO/request/ChatRoomRequestDTO.java
  src/main/java/com/partnerd/web/dto/chatRoomDTO/response/ChatRoomResponseDTO.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubActivityDTO.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubDTO.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubDetailCollabDTO.java
Labels: :bug: Fix, :sparkles: Feature

#195 [REFACTOR] api path 수정
  src/main/java/com/partnerd/web/controller/collabAskController/CollabAskRestController.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostRestController.java
Labels: :recycle: Refactor, :rocket: Chore

#198 [FIX] chatRoomMember 엔티티 연관관계 매핑 코드 수정
  src/main/java/com/partnerd/domain/mapping/ChatRoomMember.java
Labels: :bug: Fix

#201 Fix: sender, receiver 순서 수정 (#93)
  src/main/java/com/partnerd/repository/chatRoomRepository/chatRoomMember/ChatRoomMemberRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/kafkaService/KafkaProducer.java
  src/main/java/com/partnerd/web/dto/chatRoomDTO/response/ChatRoomResponseDTO.java
Labels: :bug: Fix

#203 [FIX] kafka 설정 수정
  src/main/java/com/partnerd/config/kafka/KafkaConsumerConfig.java
  src/main/java/com/partnerd/config/kafka/KafkaProducerConfig.java
  src/main/java/com/partnerd/service/kafkaService/KafkaProducer.java
Labels: :bug: Fix

#204 [FIX] ChatController 수정
  src/main/java/com/partnerd/config/kafka/KafkaConsumerConfig.java
  src/main/java/com/partnerd/web/controller/chatController/ChatController.java
Labels: :bug: Fix

#205 [FEAT] MongDB 설정 및 Chat 메세지 mongoDB 저장 및 조회
  src/main/java/com/partnerd/PartnerdApplication.java
  src/main/java/com/partnerd/config/MongoDBConfig.java
  src/main/java/com/partnerd/domain/chat/ChatMessage.java
  src/main/java/com/partnerd/domain/chat/Chatting.java
  src/main/java/com/partnerd/repository/chatRoomRepository/ChatMessageRepository.java
  src/main/java/com/partnerd/service/chatService/ChatQueryService.java
  src/main/java/com/partnerd/service/chatService/impl/ChatQueryServiceImpl.java
  src/main/java/com/partnerd/service/kafkaService/KafkaConsumer.java
  src/main/java/com/partnerd/service/kafkaService/KafkaProducer.java
  src/main/java/com/partnerd/service/kafkaService/Message.java
  src/main/java/com/partnerd/web/controller/chatController/ChatController.java
  src/main/java/com/partnerd/web/dto/chatDTO/ChatDTO.java
Labels: :sparkles: Feature

#206 [FIX] query메서드 오타 수정
  src/main/java/com/partnerd/domain/chat/ChatMessage.java
  src/main/java/com/partnerd/repository/chatRoomRepository/ChatMessageRepository.java
  src/main/java/com/partnerd/service/chatService/impl/ChatQueryServiceImpl.java
  src/main/java/com/partnerd/service/kafkaService/Message.java
Labels: :bug: Fix

#208 [FIX}chat 조회 api요청 url 수정
  src/main/java/com/partnerd/web/controller/chatController/ChatController.java
Labels: :bug: Fix

#209 [FIX]kafkaListner 설정 수정
  src/main/java/com/partnerd/service/kafkaService/KafkaConsumer.java
Labels: :bug: Fix

#211 [FIX]kafkaConsumer 역직렬화 중복 설정 오류 수정
  src/main/java/com/partnerd/config/kafka/KafkaConsumerConfig.java
Labels: :bug: Fix

#212 [FIX] localdatetime 변환 방식 통일
  src/main/java/com/partnerd/domain/chat/ChatMessage.java
  src/main/java/com/partnerd/service/chatService/impl/ChatQueryServiceImpl.java
  src/main/java/com/partnerd/service/kafkaService/KafkaConsumer.java
Labels: :bug: Fix

#202 Feat: 닉네임멤버조회 API 구현
  src/main/java/com/partnerd/repository/memberRepository/MemberRepository.java
  src/main/java/com/partnerd/repository/memberRepository/MemberRepositoryCustom.java
  src/main/java/com/partnerd/repository/memberRepository/MemberRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/clubService/ClubService.java
  src/main/java/com/partnerd/service/clubService/impl/ClubServiceImpl.java
  src/main/java/com/partnerd/web/controller/clubController/ClubRestController.java
  src/main/java/com/partnerd/web/dto/memberDTO/MemberNickNameSearchDTO.java
Labels: :sparkles: Feature

#214 [REFACTOR] kafka 설정 값 환경변수 설정
  src/main/java/com/partnerd/config/kafka/KafkaConsumerConfig.java
  src/main/java/com/partnerd/config/kafka/KafkaProducerConfig.java
  src/main/java/com/partnerd/service/kafkaService/KafkaConsumer.java
  src/main/java/com/partnerd/service/kafkaService/KafkaProducer.java
  src/main/resources/application.yml
Labels: :rocket: Chore

#216 [REFACTOR] 콜라보 요청과 채팅방 생성을 함께 처리하도록 수정
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/converter/collabAskConverter/CollabAskConverter.java
  src/main/java/com/partnerd/repository/collabAskRepository/CollabAskRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/collabAskService/CollabAskService.java
  src/main/java/com/partnerd/service/collabAskService/impl/CollabAskServiceImpl.java
  src/main/java/com/partnerd/web/controller/collabAskController/CollabAskRestController.java
  src/main/java/com/partnerd/web/dto/collabDTO/response/CollabAskResponseDTO.java
Labels: :recycle: Refactor

#213 [REFACTOR] home 화면 반환 DTO 들에 id 값 추가
  src/main/java/com/partnerd/repository/clubRepository/ClubRepositoryCustomImpl.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabPost/CollabPostRepositoryCustomImpl.java
  src/main/java/com/partnerd/repository/projectRepository/ProjectRepositoryImpl.java
  src/main/java/com/partnerd/repository/projectRepository/PromotionProjectRepositoryImpl.java
  src/main/java/com/partnerd/web/dto/homeDTO/response/HomeClubDTO.java
  src/main/java/com/partnerd/web/dto/homeDTO/response/HomeCollabPostDTO.java
  src/main/java/com/partnerd/web/dto/homeDTO/response/HomeProjectDTO.java
  src/main/java/com/partnerd/web/dto/homeDTO/response/HomePromotionProjectDTO.java
Labels: :recycle: Refactor

#217 [FIX] 콜라보 요청 시 채팅방 함께 생성 @Transactional 추가 및 쿼리 수정
  src/main/java/com/partnerd/domain/mapping/ClubMember.java
  src/main/java/com/partnerd/repository/clubMemberRepository/ClubMemberRepository.java
  src/main/java/com/partnerd/repository/collabAskRepository/CollabAskRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/chatRoomService/ChatRoomCommandService.java
  src/main/java/com/partnerd/service/chatRoomService/impl/ChatRoomCommandServiceImpl.java
  src/main/java/com/partnerd/service/collabAskService/impl/CollabAskCommandServiceImpl.java
  src/main/java/com/partnerd/service/collabAskService/impl/CollabAskServiceImpl.java
  src/main/resources/application.yml
Labels: :bug: Fix

#219 [FEAT] 다중 서버에서 웹소켓 세션 유지를 위해 redis 세션 저장 설정 추가
  build.gradle
  src/main/java/com/partnerd/config/websocket/WebSocketInterceptor.java
  src/main/java/com/partnerd/config/websocket/WebSocketMessageHandler.java
  src/main/java/com/partnerd/config/websocket/WebsocketConfig.java
  src/main/java/com/partnerd/service/kafkaService/KafkaConsumer.java
Labels: :sparkles: Feature, :recycle: Refactor

#220 [REFACTOR] 로그인시 redis에 세션 저장
  src/main/java/com/partnerd/web/controller/AuthController.java
  src/main/java/com/partnerd/web/dto/authDTO/LoginResponseDTO.java
Labels: :recycle: Refactor

#221 [FIX] 레디스 세션 확인
  src/main/java/com/partnerd/config/websocket/WebSocketInterceptor.java
Labels: :bug: Fix

#222 [FIX] 웹소켓 세션 저장 HttpSession에서 가져오는 방식으로 변경
  src/main/java/com/partnerd/config/websocket/WebSocketInterceptor.java
  src/main/java/com/partnerd/config/websocket/WebsocketConfig.java
Labels: :bug: Fix

#224 [FIX] SpringSecurity 세션 유지하는 방식으로 변경
  src/main/java/com/partnerd/config/security/SecurityConfig.java
Labels: :bug: Fix

#225 [FIX] 웹소켓 세션 저장 방식 수정
  src/main/java/com/partnerd/config/websocket/WebSocketInterceptor.java
Labels: :bug: Fix

#226 [FIX] 시큐리티 웹소켓 접속 경로 허용
  src/main/java/com/partnerd/config/security/SecurityConfig.java
Labels: :bug: Fix

#227 [FIX] 웹소켓 세션 쿼리 파라미터로 받아오는 방식으로 수정
  src/main/java/com/partnerd/config/websocket/WebSocketInterceptor.java
Labels: :bug: Fix

#229 [REFACTOR] 마이페이지 내프로필 조회 API 반환 정보 수정
  src/main/java/com/partnerd/converter/MemberConverter.java
  src/main/java/com/partnerd/service/memberService/MemberServiceImpl.java
  src/main/java/com/partnerd/web/dto/memberDTO/MemberResponseDTO.java
Labels: :recycle: Refactor

#230 [REFACTOR] UTC 시간과 KST 시간 변환 수정
  src/main/java/com/partnerd/config/websocket/WebSocketInterceptor.java
  src/main/java/com/partnerd/converter/ChatConverter.java
  src/main/java/com/partnerd/service/chatService/impl/ChatQueryServiceImpl.java
  src/main/java/com/partnerd/service/kafkaService/KafkaConsumer.java
  src/main/java/com/partnerd/service/kafkaService/KafkaProducer.java
  src/main/java/com/partnerd/service/kafkaService/Message.java
Labels: :bug: Fix, :recycle: Refactor

#233 [REFACTOR] 기본 프로필 이미지 키네임 변경 (#232)
  src/main/java/com/partnerd/service/auth/RegisterServiceImpl.java
Labels: :recycle: Refactor

#237 Refactor : 파트너드 등록 API 수정
  gradlew
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/service/clubService/impl/ClubServiceImpl.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubRegisterRequestDTO.java
Labels: :recycle: Refactor

#239 Feat: 동아리 등록 API수정
  src/main/java/com/partnerd/service/clubService/impl/ClubServiceImpl.java
Labels: :recycle: Refactor

#243 [SETTING] Prometheus 사용을 위한 의존성 추가
  build.gradle
Labels: ⚙ Setting, :butterfly: Performance

#245 [FEAT] 커뮤니티 댓글 생성/수정/삭제/조회 API 구현
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/apiPaylaod/exception/handler/CommunityCommentHandler.java
  src/main/java/com/partnerd/converter/CommunityCommentConverter.java
  src/main/java/com/partnerd/domain/Community.java
  src/main/java/com/partnerd/domain/CommunityComment.java
  src/main/java/com/partnerd/domain/Member.java
  src/main/java/com/partnerd/repository/communityCommentRepository/CommunityCommentRepository.java
  src/main/java/com/partnerd/repository/communityCommentRepository/CommunityCommentRepositoryCustom.java
  src/main/java/com/partnerd/repository/communityCommentRepository/CommunityCommentRepositoryImpl.java
  src/main/java/com/partnerd/repository/communityRepository/CommunityRepository.java
  src/main/java/com/partnerd/service/CommunityCommentService/CommunityCommentService.java
  src/main/java/com/partnerd/service/CommunityCommentService/CommunityCommentServiceImpl.java
  src/main/java/com/partnerd/web/controller/CommunityCommentController/CommunityCommentRestController.java
  src/main/java/com/partnerd/web/dto/CommunityCommentDTO/CommunityCommentRequestDTO.java
  src/main/java/com/partnerd/web/dto/CommunityCommentDTO/CommunityCommentResponseDTO.java
Labels: :sparkles: Feature

#244 [REFACTOR] 콜라보 이미지 연관관계 매핑 수정
  src/main/java/com/partnerd/domain/CollabPostImg.java
  src/main/java/com/partnerd/repository/clubMemberRepository/ClubMemberRepository.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabPost/CollabPostImgRepository.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabPostCommandServiceImpl.java
  src/main/java/com/partnerd/web/dto/collabDTO/request/CollabPostRequestDTO.java
  src/main/resources/application.yml
Labels: :recycle: Refactor

#250 [FEAT] 프로젝트 홍보글 조회 응원 여부 포함
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/converter/projectConverter/PromotionProjectConverter.java
  src/main/java/com/partnerd/service/projectService/ProjectServiceImpl.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectService.java
  src/main/java/com/partnerd/service/projectService/PromotionProjectServiceImpl.java
  src/main/java/com/partnerd/web/controller/projectController/PromotionProjectRestController.java
  src/main/java/com/partnerd/web/dto/projectDTO/PromotionProjectResponseDTO.java
Labels: :sparkles: Feature

#253 [FEAT] 동아리멤버 조회 API (더보기 클릭시)
  src/main/java/com/partnerd/repository/clubMemberRepository/ClubMemberRepository.java
  src/main/java/com/partnerd/service/clubMemberService/ClubMemberService.java
  src/main/java/com/partnerd/service/clubMemberService/ClubMemberServiceImpl.java
  src/main/java/com/partnerd/web/controller/clubController/ClubMemberRestController.java
  src/main/java/com/partnerd/web/dto/memberDTO/MemberResponseDTO.java
Labels: :sparkles: Feature

#255 [FIX] 콜라보 글 조회시 오류 해결
  src/main/java/com/partnerd/repository/collabPostRepository/collabPost/CollabPostRepository.java
Labels: :bug: Fix

#257 [FIX] 콜라보 글 작성 시, 개설한 동아리들 중 첫번째 동아리로 선택
  src/main/java/com/partnerd/repository/clubMemberRepository/ClubMemberRepository.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabInquiryCommandServiceImpl.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabPostCommandServiceImpl.java
Labels: :bug: Fix

#258 [FIX] 전체 콜라보 글 조회 시 메인 이미지 키네임 추가
  src/main/java/com/partnerd/converter/collabPostConverter/CollabPostConverter.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabPost/CollabPostRepositoryCustomImpl.java
  src/main/java/com/partnerd/web/dto/collabDTO/response/CollabPostResponseDTO.java
Labels: :bug: Fix

#260 [FIX] 파트너드 상세조회 API시 생성자 문제해결
  src/main/java/com/partnerd/web/dto/clubDTO/ClubDetailCollabDTO.java
Labels: :bug: Fix

#261 [FIX]: 파트너드 조회 API DTO Getter 추가
  src/main/java/com/partnerd/web/dto/clubDTO/ClubDetailCollabDTO.java
Labels: :bug: Fix

#263 [REFACTOR] 파트너드 팀페이지(상세조회) API 수정
  src/main/java/com/partnerd/repository/clubRepository/ClubRepositoryCustomImpl.java
Labels: :recycle: Refactor

#265 [REFACTOR] 동아리 수정 API 부리더 로직 추가
  merged_code.txt
  src/main/java/com/partnerd/repository/clubMemberRepository/ClubMemberRepository.java
  src/main/java/com/partnerd/service/clubService/impl/ClubServiceImpl.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubUpdateRequestDTO.java
Labels: :recycle: Refactor

#271 [FEAT] 마이페이지-내가쓴글 커뮤니티 조회 API 구현
  src/main/java/com/partnerd/converter/communityConverter/CommunityConverter.java
  src/main/java/com/partnerd/repository/communityRepository/CommunityRepositoryCustom.java
  src/main/java/com/partnerd/repository/communityRepository/impl/CommunityRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/communityService/CommunityQueryService.java
  src/main/java/com/partnerd/service/communityService/impl/CommunityQueryServiceImpl.java
  src/main/java/com/partnerd/web/controller/communityPostController/CommunityRestController.java
  src/main/java/com/partnerd/web/dto/CommunityDTO/CommunityResponseDTO.java
Labels: :sparkles: Feature

#269 [FIX] 콜라보 요청 삭제시 채팅방도 함께 삭제되도록 수정
  src/main/java/com/partnerd/apiPaylaod/code/status/ErrorStatus.java
  src/main/java/com/partnerd/domain/mapping/CollabAsk.java
  src/main/java/com/partnerd/service/chatRoomService/impl/ChatRoomCommandServiceImpl.java
  src/main/java/com/partnerd/service/collabAskService/impl/CollabAskServiceImpl.java
Labels: :bug: Fix

#273 [FIX] top 10 이미지 조회 시 프로필 이미지 키네임 반환 (#272)
  src/main/java/com/partnerd/converter/communityConverter/CommunityConverter.java
Labels: :bug: Fix, :recycle: Refactor

#277 [REFACTOR] 파트너드 찾기 카테고리 Id추가
  src/main/java/com/partnerd/repository/clubRepository/ClubRepositoryCustomImpl.java
  src/main/java/com/partnerd/web/dto/clubDTO/ClubDTO.java
Labels: :recycle: Refactor

#278 [REFACTOR]-파트너드목록조회 API 수정
  src/main/java/com/partnerd/converter/clubConverter/ClubConverter.java
Labels: :recycle: Refactor

#279 [FIX] 컨택트 채팅방 요청시 중복 요청 제한
  src/main/java/com/partnerd/repository/chatRoomRepository/chatRoom/ChatRoomRepository.java
  src/main/java/com/partnerd/repository/chatRoomRepository/chatRoomMember/ChatRoomMemberRepositoryCustom.java
  src/main/java/com/partnerd/repository/chatRoomRepository/chatRoomMember/ChatRoomMemberRepositoryCustomImpl.java
  src/main/java/com/partnerd/service/chatRoomService/impl/ChatRoomCommandServiceImpl.java
Labels: :bug: Fix

#280 [FIX] Jpa 메서드 제거
  src/main/java/com/partnerd/repository/chatRoomRepository/chatRoom/ChatRoomRepository.java
Labels: :bug: Fix

#281 [FIX]채팅방 중복 체크 쿼리 수정
  src/main/java/com/partnerd/repository/chatRoomRepository/chatRoomMember/ChatRoomMemberRepositoryCustomImpl.java
Labels: :bug: Fix

#283 Fix: 콜라보 문의글 프로필 이미지 추가 (#215)
  src/main/java/com/partnerd/web/dto/collabDTO/response/CollabPostResponseDTO.java
Labels: :bug: Fix

#284 [FIX] chatroom 중복 생성 방지 쿼리 수정
  src/main/java/com/partnerd/repository/chatRoomRepository/chatRoomMember/ChatRoomMemberRepositoryCustomImpl.java
Labels: :bug: Fix

#285 [FIX] kafka 역직렬화 실패시 컨슈머가 스킵하도록 에러 핸들링 설정
  src/main/java/com/partnerd/config/kafka/KafkaConsumerConfig.java
Labels: :bug: Fix

#286 [FIX] 타입 정보가 없는 메시지도 역직렬화 가능하게 설정 변경
  src/main/java/com/partnerd/config/kafka/KafkaConsumerConfig.java
Labels: :bug: Fix

#288 Fix: config 역직렬화 설정 인스턴스에서 프로퍼티 방식으로 변경 (#215)
  src/main/java/com/partnerd/config/kafka/KafkaConsumerConfig.java
Labels: :bug: Fix

#289 [FIX] kafkaListener에서 받지 못하는 문제 해결
  src/main/java/com/partnerd/config/kafka/KafkaConsumerConfig.java
  src/main/java/com/partnerd/service/kafkaService/KafkaConsumer.java
Labels: :bug: Fix

#291 [Performance] 콜라보 글 생성 쿼리 성능 개선
  src/main/java/com/partnerd/converter/collabPostConverter/CollapPostCategoryConverter.java
  src/main/java/com/partnerd/domain/mapping/CollabPostCategory.java
  src/main/java/com/partnerd/repository/categoryRepository/CategoryRepository.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabPost/CollabPostRepository.java
  src/main/java/com/partnerd/service/collabPostService/CollabPostCommandService.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabPostCommandServiceImpl.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostRestController.java
Labels: :butterfly: Performance

#293 [REFACTOR] websocket 인증 방식 redis session -> JWT token 방식으로 변경
  src/main/java/com/partnerd/config/security/SecurityConfig.java
  src/main/java/com/partnerd/config/websocket/WebSocketInterceptor.java
  src/main/java/com/partnerd/config/websocket/WebsocketConfig.java
  src/main/java/com/partnerd/service/kafkaService/KafkaConsumer.java
  src/main/java/com/partnerd/web/controller/chatController/ChatController.java
Labels: :recycle: Refactor

#294 [REFACTOR] 콜라보 글 조회 성능 개선
  src/main/java/com/partnerd/converter/collabPostConverter/CollabPostConverter.java
  src/main/java/com/partnerd/domain/mapping/ClubMember.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabPost/CollabPostRepository.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabPost/CollabPostRepositoryCustom.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabPost/CollabPostRepositoryCustomImpl.java
  src/main/java/com/partnerd/repository/collabPostRepository/collabPost/bulk/CollabPostBatchRepository.java
  src/main/java/com/partnerd/service/collabPostService/CollabPostQueryService.java
  src/main/java/com/partnerd/service/collabPostService/impl/CollabPostQueryServiceImpl.java
  src/main/java/com/partnerd/web/controller/collabPostController/CollabPostRestController.java
  src/main/java/com/partnerd/web/dto/categoryDTO/CollabPostCategoryDTO.java
  src/main/java/com/partnerd/web/dto/collabDTO/request/CollabPostRequestDTO.java
  src/main/java/com/partnerd/web/dto/collabDTO/response/CollabPostResponseDTO.java
  src/test/java/com/partnerd/CollabPostBatchInsertTest.java
Labels: :recycle: Refactor, :butterfly: Performance

#295 [REFACTOR] kafka AUTO_OFFSET_RESET_CONFIG 설정 변경
  src/main/java/com/partnerd/config/kafka/KafkaConsumerConfig.java
Labels: :bug: Fix, :recycle: Refactor, :rocket: Chore

#296 [CHORE] kafka 디버그 로그 비활성화
  src/main/java/com/partnerd/config/kafka/KafkaConsumerConfig.java
  src/main/resources/logback-spring.xml
Labels: :rocket: Chore

#298 [REFACTOR] 로그인 응답값 닉네임 추가 + 세션 아이디 삭제
  src/main/java/com/partnerd/service/auth/KakaoOAuthServiceImpl.java
  src/main/java/com/partnerd/web/controller/AuthController.java
  src/main/java/com/partnerd/web/dto/authDTO/LoginResponseDTO.java
Labels: :bug: Fix, :recycle: Refactor
